export const DEFAULT_LOCALE = 'en';

export const GET_PERSONAL_INFO = 'app/App/GET_PERSONAL_INFO';
export const GET_PERSONAL_INFO_SUCCESS = 'app/App/GET_PERSONAL_INFO_SUCCESS';
export const SET_COLUMN_DISPLAY = 'app/App/SET_COLUMN_DISPLAY';
export const FETCH_USER_NOTIFICATIONS = 'app/App/FETCH_USER_NOTIFICATIONS';
export const FETCH_USER_NOTIFICATIONS_SUCCESS =
  'app/App/FETCH_USER_NOTIFICATIONS_SUCCESS';
export const READ_USER_NOTIFICATIONS = 'app/App/READ_USER_NOTIFICATIONS';
export const READ_USER_NOTIFICATION_SUCCESS =
  'app/App/READ_USER_NOTIFICATION_SUCCESS';
export const GET_CREDENTIALS = 'app/App/GET_CREDENTIALS';
export const GET_CREDENTIALS_SUCCESS = 'app/App/GET_CREDENTIALS_SUCCESS';
export const TOGGLE_SIDEBAR_DISPLAY = 'app/App/TOGGLE_SIDEBAR_DISPLAY';

// Top-up related constants
export const GET_TOP_UP_PRICING_LIST = 'app/App/GET_TOP_UP_PRICING_LIST';
export const GET_TOP_UP_PRICING_LIST_SUCCESS =
  'app/App/GET_TOP_UP_PRICING_LIST_SUCCESS';
export const GET_TOP_UP_PRICING_COST = 'app/App/GET_TOP_UP_PRICING_COST';
export const GET_TOP_UP_PRICING_COST_SUCCESS =
  'app/App/GET_TOP_UP_PRICING_COST_SUCCESS';
export const GET_TOP_UP_REQUEST = 'app/App/GET_TOP_UP_REQUEST';
export const GET_TOP_UP_CHECKOUT_SESSION = 'app/App/GET_TOP_UP_CHECKOUT_SESSION';
export const GET_TOP_UP_CHECKOUT_SESSION_SUCCESS = 'app/App/GET_TOP_UP_CHECKOUT_SESSION_SUCCESS';
export const GET_STRIPE_CONFIG = 'app/App/GET_STRIPE_CONFIG';
export const GET_STRIPE_CONFIG_SUCCESS = 'app/App/GET_STRIPE_CONFIG_SUCCESS';

// Subscription related constants
export const GET_PLANS = 'app/App/GET_PLANS';
export const GET_PLANS_SUCCESS = 'app/App/GET_PLANS_SUCCESS';
export const SUBSCRIBE_REQUEST = 'app/App/SUBSCRIBE_REQUEST';
export const SUBSCRIBE_PLAN = 'app/App/SUBSCRIBE_PLAN';
export const SUBSCRIBE_PLAN_SUCCESS = 'app/App/SUBSCRIBE_PLAN_SUCCESS';
export const GET_SUBSCRIPTION = 'app/App/GET_SUBSCRIPTION';
export const GET_SUBSCRIPTION_SUCCESS = 'app/App/GET_SUBSCRIPTION_SUCCESS';
export const TOP_UP = 'app/App/TOP_UP';
export const TOP_UP_SUCCESS = 'app/App/TOP_UP_SUCCESS';
export const CANCEL_SUBSCRIPTION = 'app/App/CANCEL_SUBSCRIPTION';
export const CANCEL_SUBSCRIPTION_SUCCESS = 'app/App/CANCEL_SUBSCRIPTION_SUCCESS';
export const CANCEL_SUBSCRIPTION_ERROR = 'app/App/CANCEL_SUBSCRIPTION_ERROR';
export const GET_SUBSCRIPTION_CHECKOUT_SESSION = 'app/App/GET_SUBSCRIPTION_CHECKOUT_SESSION';
export const GET_SUBSCRIPTION_CHECKOUT_SESSION_SUCCESS = 'app/App/GET_SUBSCRIPTION_CHECKOUT_SESSION_SUCCESS';
export const GET_PLAN_AMOUNT = 'app/App/GET_PLAN_AMOUNT';
export const GET_PLAN_AMOUNT_SUCCESS = 'app/App/GET_PLAN_AMOUNT_SUCCESS';
export const RESET_PLAN_AMOUNT = 'app/App/RESET_PLAN_AMOUNT';

// Payment related constants
export const GET_PAYMENTS = 'app/App/GET_PAYMENTS';
export const GET_PAYMENTS_SUCCESS = 'app/App/GET_PAYMENTS_SUCCESS';

//  User Profile related constants
export const GET_USER_PROFILE = 'app/App/GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'app/App/GET_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE = 'app/App/UPDATE_USER_PROFILE';
export const UPDATE_USER_PROFILE_SUCCESS = 'app/App/UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_ERROR = 'app/App/UPDATE_USER_PROFILE_ERROR';
export const SEND_EMAIL_VERIFICATION_CODE = 'app/App/SEND_EMAIL_VERIFICATION_CODE';
export const SEND_EMAIL_VERIFICATION_CODE_SUCCESS = 'app/App/SEND_EMAIL_VERIFICATION_CODE_SUCCESS';
export const SEND_EMAIL_VERIFICATION_CODE_ERROR = 'app/App/SEND_EMAIL_VERIFICATION_CODE_ERROR';
export const CHANGE_PASSWORD = 'app/App/CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'app/App/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'app/App/CHANGE_PASSWORD_ERROR';
export const GET_CREDITS_USAGE = 'app/App/GET_CREDITS_USAGE';
export const GET_CREDITS_USAGE_SUCCESS = 'app/App/GET_CREDITS_USAGE_SUCCESS';
export const GET_USERS_INFO = 'app/App/GET_USERS_INFO';
export const GET_USERS_INFO_SUCCESS = 'app/App/GET_USERS_INFO_SUCCESS';
export const ADD_USER_INVITATION = 'app/App/ADD_USER_INVITATION';
export const ADD_USER_INVITATION_SUCCESS = 'app/App/ADD_USER_INVITATION_SUCCESS';
export const ADD_USER_INVITATION_ERROR = 'app/App/ADD_USER_INVITATION_ERROR';
export const UPDATE_MANAGE_USER = 'app/App/UPDATE_MANAGE_USER';
export const UPDATE_MANAGE_USER_SUCCESS = 'app/App/UPDATE_MANAGE_USER_SUCCESS';
export const ACTIVATE_OR_DEACTIVATE_MANAGE_USER = 'app/App/ACTIVATE_OR_DEACTIVATE_MANAGE_USER';
export const ACTIVATE_OR_DEACTIVATE_MANAGE_USER_SUCCESS = 'app/App/ACTIVATE_OR_DEACTIVATE_MANAGE_USER_SUCCESS';
export const GET_EMAIL_ADDRESSES = 'app/App/GET_EMAIL_ADDRESSES';
export const GET_EMAIL_ADDRESSES_SUCCESS = 'app/App/GET_EMAIL_ADDRESSES_SUCCESS';
